export default {
    Register: "https://buildbridge-bakend.onrender.com/user/register",
    Login:"https://buildbridge-bakend.onrender.com/user/login",
    Get_All_Projects:"https://buildbridge-bakend.onrender.com/user/",
    Get_myProject:"https://buildbridge-bakend.onrender.com/user/project/my-projects",
    Get_projectByID:"https://buildbridge-bakend.onrender.com/user/project/",
    Add_project:"https://buildbridge-bakend.onrender.com/user/projects",
    Get_Tech:"https://buildbridge-bakend.onrender.com/user/project/technology",
    Get_profile:"https://buildbridge-bakend.onrender.com/user/profile/",
    Update_profile:"https://buildbridge-bakend.onrender.com/user/profile",
    Add_Education:"https://buildbridge-bakend.onrender.com/user/add-education",
    Get_Eductaion:"https://buildbridge-bakend.onrender.com/user/education/",
     Add_Skill:"https://buildbridge-bakend.onrender.com/user/addskill",
     Get_Skills :"https://buildbridge-bakend.onrender.com/user/skill/",
     Update_Skill:"https://buildbridge-bakend.onrender.com/user/updateskill/",
     Delete_Skill:"https://buildbridge-bakend.onrender.com/user/deleteskill/",
       Delete_Education:"https://buildbridge-bakend.onrender.com/user/delete/",
        Update_Education:"https://buildbridge-bakend.onrender.com/user/update/",
        Delete_project:"https://buildbridge-bakend.onrender.com/user/project/",
        Update_Project:"https://buildbridge-bakend.onrender.com/user/project/",
        GetAcceptedMembers:"https://buildbridge-bakend.onrender.com/members/",
        UpdateMemberRole:"https://buildbridge-bakend.onrender.com/members/",
        RemoveMEmber:"https://buildbridge-bakend.onrender.com/members/",
        Send_Collab_Req:"https://buildbridge-bakend.onrender.com/collaboration/send",
        Get_Notifications:"https://buildbridge-bakend.onrender.com/notify/",
        Accept_Collab_Req:"https://buildbridge-bakend.onrender.com/collaboration/",
         LeaveProject:"https://buildbridge-bakend.onrender.com/members/leave/",
         SendMessages:"https://buildbridge-bakend.onrender.com/messages",
         GetMesaages:"https://buildbridge-bakend.onrender.com/messages/",
         Firebase:"https://buildbridge-bakend.onrender.com/user/firebase-login",
          Forgot_Password:"https://buildbridge-bakend.onrender.com/user/forgot-password",
          Reset_password:"https://buildbridge-bakend.onrender.com/user/reset-password",
           VerifyOtp:"https://buildbridge-bakend.onrender.com/user/verify-otp",
          MarkAllRead :"https://buildbridge-bakend.onrender.com/notify/mark-all-read"
  
}